# Regexes with \. should be \\. inside the TOML parser

[URL_COMPLEX]
regex = "http:/google\\.github\\.io/[a-z]{10}/version[0-9]{3}/doxygen/html/[a-z0-9]{20}\\.html"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "UrlCompress", "PextUrlComplex", "OffXorUrlComplex", "OffXorSimdUrlComplex", "NaiveSimdUrlComplex", "GptUrlComplex", "GperfUrlComplex", "NaiveUrlComplex", "PextMurmurUrlComplex"]

[URL_FIXED_PATTERN]
regex = "http:/google\\.github\\.io/farmhash/doxygen/html/[a-z0-9]{20}\\.html"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextUrl", "OffXorUrl", "OffXorSimdUrl", "NaiveUrl", "GptUrl", "GperfUrl", "NaiveSimdUrl"]

[MAC]
regex = "([0-9a-fA-F]{2}-){5}[0-9a-fA-F]{2}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "MacAddressHashBitOps" , "PextMac", "OffXorMac", "NaiveMac", "GptMac", "GperfMac"]

[CPF]
regex = "(([0-9]{3})\\.){2}[0-9]{3}-[0-9]{2}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "CPFHashBitOps", "CPFHashVectorizedMul", "PextCPF", "OffXorCPF", "NaiveCPF", "GptCPF", "GperfCPF"]

[SSN]
regex = "[0-9]{3}-[0-9]{2}-[0-9]{4}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "SSNHashBitOps", "PextSSN", "OffXorSSN", "NaiveSSN", "GptSSN", "GperfSSN"]

[IPV4]
regex = "(([0-9]{3})\\.){3}[0-9]{3}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "IPV4HashMove", "IPV4HashUnrolled", "IPV4HashBitOps", "PextIPV4", "OffXorIPV4", "NaiveIPV4", "GptIPV4", "GperfIPV4"]

[IPV6]
regex = "([0-9a-fA-F]{4}:){7}[0-9a-fA-F]{4}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "PextIPV6", "OffXorIPV6", "OffXorSimdIPV6", "NaiveIPV6", "GptIPV6", "GperfIPV6", "NaiveSimdIPV6"]

[INTS]
regex = "[0-9]{100}"
hashes = ["STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "IntBitHash", "IntSimdHash", "PextINTS", "OffXorINTS", "OffXorSimdINTS", "NaiveINTS", "GptINTS", "GperfINTS", "NaiveSimdINTS", "PextMurmurINTS"]
