# Regexes with \. should be \\. inside the TOML parser


[URL_COMPLEX]
regex = "http:/google\\.github\\.io/[a-z]{10}/version[0-9]{3}/doxygen/html/[a-z0-9]{20}\\.html"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash", "UrlCompress", "UrlSynth"]

[URL_GENERIC]
regex = "https://www\\.[!~]{100,200}"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash", "UrlGenericHashBitOps"]

[URL_FIXED_PATTERN]
regex = "http:/google.github.io/farmhash/doxygen/html/[a-z0-9]{20}\\.html"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash", "UrlGenericHashBitOps"]

[URL_FIXED_PATTERN_INTERNAL]
regex = "[a-z0-9]{20}"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash", "UrlGenericHashBitOps"]

[MAC]
regex = "([0-9a-fA-F]{2}-){5}[0-9a-fA-F]{2}"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash", "MacAddressHashBitOps"]

[CPF]
regex = "(([0-9]{3})\\.){2}[0-9]{3}-[0-9]{2}"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash",  "CPFHashBitOps", "CPFHashVectorizedMul"]

[SSN]
regex = "[0-9]{3}-[0-9]{2}-[0-9]{4}"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash",  "SSNHashBitOps"]

[IPV4]
regex = "(([0-9]{3})\\.){3}[0-9]{3}"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash", "IPV4HashGeneric", "IPV4HashMove", "IPV4HashUnrolled", "IPV4HashBitOps"]

[IPV6]
regex = "([0-9a-fA-F]{4}:){7}[0-9a-fA-F]{4}"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash", "IPV4HashGeneric"]

[INTS]
regex = "[0-9]{100}"
hashes = ["STDHash",  "STDHashMurmur", "FNVHash", "IntBitHash", "IntSimdHash"]
