# Regexes with \. should be \\. inside the TOML parser

[URL_COMPLEX]
regex = "http:/google\\.github\\.io/[a-z]{10}/version[0-9]{3}/doxygen/html/[a-z0-9]{20}\\.html"
hashes = ["STDHashBin",  "STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "UrlCompress", "SynthUrlComplex", "NaiveSimdUrlComplex", "NaiveUrlComplex"]

[URL_FIXED_PATTERN]
regex = "http:/google\\.github\\.io/farmhash/doxygen/html/[a-z0-9]{20}\\.html"
hashes = ["STDHashBin",  "STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "SynthUrl", "NaiveUrl", "NaiveSimdUrl"]

[URL_FIXED_PATTERN_INTERNAL]
regex = "[a-z0-9]{20}"
hashes = ["STDHashBin",  "STDHashSrc", "AbseilHash", "CityHash", "FNVHash"]

[MAC]
regex = "([0-9a-fA-F]{2}-){5}[0-9a-fA-F]{2}"
hashes = ["STDHashBin",  "STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "MacAddressHashBitOps" , "SynthMac", "NaiveMac"]

[CPF]
regex = "(([0-9]{3})\\.){2}[0-9]{3}-[0-9]{2}"
hashes = ["STDHashBin",  "STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "CPFHashBitOps", "CPFHashVectorizedMul", "SynthCPF", "NaiveCPF"]

[SSN]
regex = "[0-9]{3}-[0-9]{2}-[0-9]{4}"
hashes = ["STDHashBin",  "STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "SSNHashBitOps", "SynthSSN", "NaiveSSN"]

[IPV4]
regex = "(([0-9]{3})\\.){3}[0-9]{3}"
hashes = ["STDHashBin",  "STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "IPV4HashMove", "IPV4HashUnrolled", "IPV4HashBitOps", "SynthIPV4", "NaiveIPV4"]

[IPV6]
regex = "([0-9a-fA-F]{4}:){7}[0-9a-fA-F]{4}"
hashes = ["STDHashBin",  "STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "SynthIPV6", "NaiveIPV6", "NaiveSimdIPV6"]

[INTS]
regex = "[0-9]{100}"
hashes = ["STDHashBin",  "STDHashSrc", "AbseilHash", "CityHash", "FNVHash", "IntBitHash", "IntSimdHash", "SynthINTS", "NaiveINTS", "NaiveSimdINTS"]
