[package]
name = "sepe-runner"
version = "0.1.0"
edition = "2021"
authors = ["Leonardo G. Faé", "Renato B. Hoffmann"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
toml = {version = "0.8", default_features = false, features = ["parse"] }
